# Generated by Django 4.2.23 on 2025-08-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=50)),
                ('skeletal_element', models.CharField(blank=True, max_length=5, null=True)),
                ('element', models.CharField(blank=True, choices=[('CR', 'Cranial'), ('CD', 'Craniodental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], max_length=50, null=True)),
                ('type', models.CharField(choices=[('C', 'Continuous'), ('D', 'Discrete')], max_length=50)),
                ('designation', models.CharField(choices=[('TAX', 'Taxonomic'), ('PHL', 'Phylogenetic'), ('BOTH', 'Both')], max_length=50)),
                ('state_code', models.CharField(default='', max_length=20)),
                ('states_types', models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('SM', 'Small'), ('I', 'Intermediate'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large'), ('LATFLARE', 'Lateral flare wth posterior protrusion')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
