# Generated by Django 4.2.23 on 2025-08-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='states_types',
        ),
        migrations.AddField(
            model_name='character',
            name='state_type',
            field=models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('SM', 'Small'), ('I', 'Intermediate'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large'), ('LATFLARE', 'Lateral flare wth posterior protrusion')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='designation',
            field=models.CharField(choices=[('TAX', 'Taxonomic'), ('PHL', 'Phylogenetic'), ('BOTH', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(blank=True, choices=[('CR', 'Cranial'), ('CD', 'Craniodental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='state_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('C', 'Continuous'), ('D', 'Discrete')], max_length=100),
        ),
    ]
