# Generated by Django 4.2.23 on 2025-08-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0002_remove_character_states_types_character_state_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='uberon_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
