# Generated by Django 4.2.23 on 2025-08-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0003_character_uberon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='designation',
            new_name='character_designation',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='type',
            new_name='character_type',
        ),
    ]
