# Generated by Django 4.2.23 on 2025-08-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0004_rename_designation_character_character_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='taxa_found',
            field=models.CharField(choices=[('AA', 'Australopithecus afarensis'), ('ANA', 'Australopithecus anamensis')], max_length=200, null=True),
        ),
    ]
