# Generated by Django 4.2.23 on 2025-09-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0005_character_taxa_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='state_type',
        ),
        migrations.AddField(
            model_name='character',
            name='continuous_state_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='discrete_state_type',
            field=models.CharField(choices=[('A', 'Absent'), ('P', 'Present'), ('SM', 'Small'), ('I', 'Intermediate'), ('M', 'Medium'), ('L', 'Large'), ('VL', 'Very Large')], max_length=100, null=True),
        ),
    ]
