# Generated by Django 4.2.23 on 2025-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0006_remove_character_state_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='taxa_found',
            field=models.CharField(choices=[('AA', 'Australopithecus afarensis'), ('ANA', 'Australopithecus anamensis'), ('PA', 'Paranthropus aethiopicus'), ('PB', 'Paranthropus boisei')], max_length=200, null=True),
        ),
    ]
