# Generated by Django 4.2.23 on 2025-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0007_alter_character_taxa_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='continuous_state_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='discrete_state_type',
        ),
        migrations.AddField(
            model_name='character',
            name='multistate_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='number_of_states',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_code',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.CharField(choices=[('C', 'Continuous'), ('D', 'Discrete'), ('UM', 'Unordered Multistate'), ('OM', 'Ordered Multistate'), ('IN', 'Integer'), ('RN', 'Real Number')], max_length=100),
        ),
    ]
