# Generated by Django 4.2.23 on 2025-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0008_remove_character_continuous_state_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
