# Generated by Django 4.2.23 on 2025-09-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0009_alter_character_character_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='element',
            new_name='anatomical_region',
        ),
    ]
