# Generated by Django 4.2.23 on 2025-09-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0010_rename_element_character_anatomical_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='character',
        ),
    ]
