# Generated by Django 4.2.23 on 2025-09-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0011_rename_name_character_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='anatomical_region',
            field=models.CharField(blank=True, choices=[('CR', 'Cranial'), ('CD', 'Craniodental'), ('DEN', 'Dental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], max_length=100, null=True),
        ),
    ]
