# Generated by Django 4.2.23 on 2025-09-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0012_alter_character_anatomical_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='order_type',
            field=models.CharField(blank=True, choices=[('UM', 'Unordered Multistate'), ('OM', 'Ordered Multistate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_designation',
            field=models.CharField(blank=True, choices=[('TAX', 'Taxonomic'), ('PHL', 'Phylogenetic'), ('BOTH', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.CharField(blank=True, choices=[('C', 'Continuous'), ('D', 'Discrete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='taxa_found',
            field=models.CharField(blank=True, choices=[('AA', 'Australopithecus afarensis'), ('ANA', 'Australopithecus anamensis'), ('PA', 'Paranthropus aethiopicus'), ('PB', 'Paranthropus boisei')], max_length=200, null=True),
        ),
    ]
