# Generated by Django 4.2.23 on 2025-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0013_character_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='character',
            name='multistate_type',
            field=models.CharField(blank=True, choices=[('UM', 'Unordered Multistate'), ('OM', 'Ordered Multistate')], max_length=100),
        ),
    ]
