# Generated by Django 4.2.23 on 2025-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0014_remove_character_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_significance',
            field=models.CharField(blank=True, choices=[('D', 'Diagnostic'), ('ND', 'Non-diagnostic')], max_length=50, null=True),
        ),
    ]
