# Generated by Django 4.2.23 on 2025-10-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0015_character_character_significance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fossil_id', models.CharField(help_text='Unique identifier for the fossil specimen', max_length=50, unique=True)),
                ('element_type', models.CharField(help_text='Type of skeletal element (e.g., femur, cranium, mandible)', max_length=100)),
                ('anatomical_region', models.CharField(choices=[('CR', 'Cranial'), ('CD', 'Craniodental'), ('DEN', 'Dental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], help_text='Anatomical region of the fossil', max_length=100)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_state', models.ForeignKey(blank=True, help_text='Associated character state selection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fossils', to='hcdb.character')),
            ],
            options={
                'verbose_name': 'Fossil',
                'verbose_name_plural': 'Fossils',
                'ordering': ['fossil_id'],
            },
        ),
    ]
