# Generated by Django 4.2.23 on 2025-10-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0016_fossil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='Code for this state (e.g., 0, 1, 2, A, B)', max_length=10)),
                ('state_name', models.CharField(help_text='Name/label of the state', max_length=100)),
                ('state_description', models.TextField(blank=True, help_text='Detailed description of this state', null=True)),
                ('state_order', models.IntegerField(blank=True, default=0, help_text='Order of this state (for ordered multistate characters)', null=True)),
                ('is_derived', models.BooleanField(blank=True, default=False, help_text='Whether this is a derived state', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(help_text='The character this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hcdb.character')),
            ],
            options={
                'verbose_name': 'Character State',
                'verbose_name_plural': 'Character States',
                'ordering': ['character', 'state_order', 'state_code'],
                'unique_together': {('character', 'state_code')},
            },
        ),
    ]
