# Generated by Django 4.2.23 on 2025-10-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0017_characterstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fossil',
            name='character_state',
        ),
        migrations.CreateModel(
            name='FossilCharacterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(blank=True, choices=[('HIGH', 'High Confidence'), ('MEDIUM', 'Medium Confidence'), ('LOW', 'Low Confidence'), ('UNCERTAIN', 'Uncertain')], help_text='Confidence level of this character state assignment', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this specific character state observation', null=True)),
                ('assigned_by', models.CharField(blank=True, help_text='Person who assigned this state', max_length=100, null=True)),
                ('assigned_date', models.DateField(blank=True, help_text='Date when this state was assigned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_state', models.ForeignKey(help_text='The character state observed in this fossil', on_delete=django.db.models.deletion.CASCADE, related_name='fossil_character_states', to='hcdb.characterstate')),
                ('fossil', models.ForeignKey(help_text='The fossil specimen', on_delete=django.db.models.deletion.CASCADE, related_name='fossil_character_states', to='hcdb.fossil')),
            ],
            options={
                'verbose_name': 'Fossil Character State',
                'verbose_name_plural': 'Fossil Character States',
                'ordering': ['fossil', 'character_state__character', 'character_state__state_order'],
                'unique_together': {('fossil', 'character_state')},
            },
        ),
        migrations.AddField(
            model_name='fossil',
            name='character_states',
            field=models.ManyToManyField(blank=True, help_text='Character states associated with this fossil', related_name='fossils', through='hcdb.FossilCharacterState', to='hcdb.characterstate'),
        ),
    ]
