# Generated by Django 4.2.23 on 2025-10-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0018_remove_fossil_character_state_fossilcharacterstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_code',
        ),
    ]
