# Generated by Django 4.2.23 on 2025-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0019_remove_character_character_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='anatomical_region',
            field=models.CharField(blank=True, choices=[('CR', 'Cranial'), ('DEN', 'Dental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='anatomical_region',
            field=models.CharField(choices=[('CR', 'Cranial'), ('DEN', 'Dental'), ('CF', 'Craniofacial'), ('PC', 'Postcranial')], help_text='Anatomical region of the fossil', max_length=100),
        ),
    ]
