# Generated by Django 4.2.23 on 2025-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0020_alter_character_anatomical_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_designation',
            field=models.CharField(blank=True, choices=[('TAX', 'Taxonomic'), ('PHY', 'Phylogenetic'), ('BOTH', 'Both')], max_length=50, null=True),
        ),
    ]
