# Generated by Django 4.2.23 on 2025-10-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0021_alter_character_character_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skeletal_element',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
