# Generated by Django 4.2.23 on 2025-10-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0022_alter_character_skeletal_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='state_code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
