# Generated by Django 4.2.23 on 2025-10-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0023_alter_character_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
