# Generated by Django 4.2.23 on 2025-10-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0024_alter_character_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
