# Generated by Django 4.2.23 on 2025-10-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0025_alter_character_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
