# Generated by Django 4.2.23 on 2025-10-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0026_alter_character_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='state_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
