# Generated by Django 4.2.23 on 2025-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0027_alter_character_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skeletal_element',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
