# Generated by Django 4.2.23 on 2025-10-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0028_alter_character_skeletal_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fossil',
            name='taxon',
            field=models.CharField(blank=True, help_text='Taxonomic name of the fossil', max_length=100),
        ),
        migrations.AddField(
            model_name='fossil',
            name='uberon_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='element_type',
            field=models.CharField(blank=True, help_text='Type of skeletal element (e.g., femur, cranium, mandible)', max_length=100),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='fossil_id',
            field=models.CharField(blank=True, help_text='Catalog Number for the fossil specimen', max_length=50, unique=True),
        ),
    ]
