# Generated by Django 4.2.23 on 2025-10-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0029_fossil_age_fossil_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='taxon',
            field=models.TextField(blank=True, help_text='Taxonomic name of the fossil', max_length=100),
        ),
    ]
