# Generated by Django 4.2.23 on 2025-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0035_alter_fossil_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
