# Generated by Django 4.2.23 on 2025-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdb', '0037_alter_fossil_taxon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='taxa_found',
            field=models.CharField(blank=True, choices=[('AA', 'Australopithecus afarensis'), ('ANA', 'Australopithecus anamensis'), ('PA', 'Paranthropus aethiopicus'), ('PB', 'Paranthropus boisei'), ('A', 'Australopithecus'), ('H', 'Hominini'), ('HH', 'Homo habils'), ('HE', 'Homo erectus'), ('HO', 'Homo'), ('HER', 'Homo ergaster'), ('KP', 'Kenyanthropus platyops')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='taxon',
            field=models.CharField(blank=True, choices=[('AA', 'Australopithecus afarensis'), ('ANA', 'Australopithecus anamensis'), ('PA', 'Paranthropus aethiopicus'), ('PB', 'Paranthropus boisei'), ('A', 'Australopithecus'), ('H', 'Hominini'), ('HH', 'Homo habils'), ('HE', 'Homo erectus'), ('HO', 'Homo'), ('HER', 'Homo ergaster'), ('KP', 'Kenyanthropus platyops')], help_text='Taxonomic name of the fossil', max_length=100),
        ),
    ]
